"""Initial migration

Revision ID: 2bb775576322
Revises: 
Create Date: 2025-05-27 23:50:13.383409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bb775576322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol')
    op.drop_table('sys_config')
    op.drop_table('external_info')
    op.drop_index(op.f('fix_symbol'), table_name='external_symbol_info')
    op.drop_index(op.f('idx_external_symbol_info_external_id'), table_name='external_symbol_info')
    op.drop_index(op.f('idx_external_symbol_info_fix_symbol'), table_name='external_symbol_info')
    op.create_index(op.f('ix_external_symbol_info_external_id'), 'external_symbol_info', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_symbol_info_fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=True)
    op.create_index(op.f('ix_external_symbol_info_id'), 'external_symbol_info', ['id'], unique=False)
    op.drop_column('external_symbol_info', 'updated_at')
    op.drop_column('external_symbol_info', 'created_at')
    op.drop_index(op.f('uc_symbol_name'), table_name='groups')
    op.create_unique_constraint('_symbol_name_uc', 'groups', ['symbol', 'name'])
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_user_orders_id'), 'user_orders', ['id'], unique=False)
    op.create_index(op.f('ix_user_orders_order_id'), 'user_orders', ['order_id'], unique=True)
    op.create_unique_constraint('_email_phone_user_type_uc', 'users', ['email', 'phone_number', 'user_type'])
    op.create_index(op.f('ix_users_account_number'), 'users', ['account_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_group_name'), 'users', ['group_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_reffered_code'), 'users', ['reffered_code'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_transaction_id'), 'wallets', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_transaction_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_users_reffered_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_group_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_number'), table_name='users')
    op.drop_constraint('_email_phone_user_type_uc', 'users', type_='unique')
    op.drop_index(op.f('ix_user_orders_order_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_id'), table_name='user_orders')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_constraint('_symbol_name_uc', 'groups', type_='unique')
    op.create_index(op.f('uc_symbol_name'), 'groups', ['symbol', 'name'], unique=True)
    op.add_column('external_symbol_info', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('external_symbol_info', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_external_symbol_info_id'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_fix_symbol'), table_name='external_symbol_info')
    op.drop_index(op.f('ix_external_symbol_info_external_id'), table_name='external_symbol_info')
    op.create_index(op.f('idx_external_symbol_info_fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=False)
    op.create_index(op.f('idx_external_symbol_info_external_id'), 'external_symbol_info', ['external_id'], unique=False)
    op.create_index(op.f('fix_symbol'), 'external_symbol_info', ['fix_symbol'], unique=True)
    op.create_table('external_info',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_config',
    sa.Column('variable', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('set_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('set_by', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('variable'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('symbol',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pips', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('spread_pip', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('market_price', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('show_points', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('profit_currency', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
