"""Add security_answer to users and demo_users tables, and update wallet/otp foreign keys

Revision ID: c4ed0636da48
Revises: 580b978e44fb
Create Date: 2025-05-29 10:28:24.308809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4ed0636da48'
down_revision: Union[str, None] = '580b978e44fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('demo_user_id', sa.Integer(), nullable=True))
    op.alter_column('otps', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_otps_demo_user_id'), 'otps', ['demo_user_id'], unique=False)
    op.create_foreign_key(None, 'otps', 'demo_users', ['demo_user_id'], ['id'])
    op.add_column('users', sa.Column('security_answer', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('demo_user_id', sa.Integer(), nullable=True))
    op.alter_column('wallets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_wallets_demo_user_id'), 'wallets', ['demo_user_id'], unique=False)
    op.create_foreign_key(None, 'wallets', 'demo_users', ['demo_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_index(op.f('ix_wallets_demo_user_id'), table_name='wallets')
    op.alter_column('wallets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('wallets', 'demo_user_id')
    op.drop_column('users', 'security_answer')
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.drop_index(op.f('ix_otps_demo_user_id'), table_name='otps')
    op.alter_column('otps', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('otps', 'demo_user_id')
    # ### end Alembic commands ###
