"""Add id_counter

Revision ID: defafa4db0d5
Revises: b345766ba261
Create Date: 2025-07-14 22:05:48.076822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'defafa4db0d5'
down_revision: Union[str, None] = 'b345766ba261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_user_orders_id'), table_name='userorders')
    op.drop_index(op.f('ix_user_orders_order_id'), table_name='userorders')
    op.drop_table('userorders')
    op.create_index(op.f('ix_demo_user_orders_cancel_id'), 'demo_user_orders', ['cancel_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_close_id'), 'demo_user_orders', ['close_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_modify_id'), 'demo_user_orders', ['modify_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_stoploss_cancel_id'), 'demo_user_orders', ['stoploss_cancel_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_stoploss_id'), 'demo_user_orders', ['stoploss_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_takeprofit_cancel_id'), 'demo_user_orders', ['takeprofit_cancel_id'], unique=False)
    op.create_index(op.f('ix_demo_user_orders_takeprofit_id'), 'demo_user_orders', ['takeprofit_id'], unique=False)
    op.create_index(op.f('ix_user_orders_cancel_id'), 'user_orders', ['cancel_id'], unique=True)
    op.create_index(op.f('ix_user_orders_close_id'), 'user_orders', ['close_id'], unique=True)
    op.create_index(op.f('ix_user_orders_modify_id'), 'user_orders', ['modify_id'], unique=True)
    op.create_index(op.f('ix_user_orders_stoploss_cancel_id'), 'user_orders', ['stoploss_cancel_id'], unique=True)
    op.create_index(op.f('ix_user_orders_stoploss_id'), 'user_orders', ['stoploss_id'], unique=True)
    op.create_index(op.f('ix_user_orders_takeprofit_cancel_id'), 'user_orders', ['takeprofit_cancel_id'], unique=True)
    op.create_index(op.f('ix_user_orders_takeprofit_id'), 'user_orders', ['takeprofit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_orders_takeprofit_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_takeprofit_cancel_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_stoploss_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_stoploss_cancel_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_modify_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_close_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_cancel_id'), table_name='user_orders')
    op.drop_index(op.f('ix_demo_user_orders_takeprofit_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_takeprofit_cancel_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_stoploss_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_stoploss_cancel_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_modify_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_close_id'), table_name='demo_user_orders')
    op.drop_index(op.f('ix_demo_user_orders_cancel_id'), table_name='demo_user_orders')
    op.create_table('userorders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('order_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_company_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('order_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('order_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('order_price', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('order_quantity', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('contract_value', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('margin', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('close_price', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('net_profit', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('swap', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('commission', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('cancel_message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('close_message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cancel_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('close_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('modify_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stoploss_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('takeprofit_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stoploss_cancel_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('takeprofit_cancel_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], name=op.f('userorders_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_orders_order_id'), 'userorders', ['order_id'], unique=True)
    op.create_index(op.f('ix_user_orders_id'), 'userorders', ['id'], unique=False)
    op.drop_table('id_counter')
    # ### end Alembic commands ###
